# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ind_list_Rcpp <- function(regime, n_regimes) {
    .Call(`_mvb_detector_get_ind_list_Rcpp`, regime, n_regimes)
}

#' Parallel sampling of mixture indicators
#'
#' @keywords internal
sample_r_i_mat <- function(U, z_min_eta, m_mix, tmp1, tmp2) {
    .Call(`_mvb_detector_sample_r_i_mat`, U, z_min_eta, m_mix, tmp1, tmp2)
}

#' Log of the prior on alpha conditionally on the change points
#' 
#' @param alpha_star Matrix of unique values of alpha over each time interval
#' @param mu_alpha Mean of the marginal prior on alpha
#' @param s2_alpha Variance of the marginal prior on alpha
#' 
#' @keywords internal
#' @name log_prior_alpha
NULL

#' Log of the hazard rate
#'
#' @param alpha Vector of baseline hazard parameters
#'
#' @keywords internal
log_hazard_rate_compete <- function(alpha) {
    .Call(`_mvb_detector_log_hazard_rate_compete`, alpha)
}

log_likelihood <- function(n_vec, alpha_star, event, time_to_event, cens, mu) {
    .Call(`_mvb_detector_log_likelihood`, n_vec, alpha_star, event, time_to_event, cens, mu)
}

#' Log of posterior for discrete-time survival with `n_risk` risks
#' 
#' Here, the prior on cause-specific change points p(z_t | gamma_t) is not
#' included in `log_prior_n_vec`, and thus not included in this log-posterior
#' computation.
#' 
#' @keywords internal
log_posterior_unaugmented <- function(n_vec, alpha_star, beta, X, time_to_event, event, cens, log_prior_n_vec, mu_alpha, s2_alpha) {
    .Call(`_mvb_detector_log_posterior_unaugmented`, n_vec, alpha_star, beta, X, time_to_event, event, cens, log_prior_n_vec, mu_alpha, s2_alpha)
}

sample_int <- function(n) {
    .Call(`_mvb_detector_sample_int`, n)
}

sample_z <- function(n_risk) {
    .Call(`_mvb_detector_sample_z`, n_risk)
}

update_n_vec_global <- function(n_vec, alpha_star, z_star, beta, time_to_event, event, cens, X, n_risk, t_max, log_prior_n_vec, mu_alpha, s2_alpha) {
    .Call(`_mvb_detector_update_n_vec_global`, n_vec, alpha_star, z_star, beta, time_to_event, event, cens, X, n_risk, t_max, log_prior_n_vec, mu_alpha, s2_alpha)
}

update_z_global <- function(log_post, n_vec, alpha_star, z_star, beta, time_to_event, event, cens, X, n_risk, log_prior_n_vec, mu_alpha, s2_alpha) {
    .Call(`_mvb_detector_update_z_global`, log_post, n_vec, alpha_star, z_star, beta, time_to_event, event, cens, X, n_risk, log_prior_n_vec, mu_alpha, s2_alpha)
}

